apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-configmap
      containers:
        - name: nginx
          image: nginx:latest
          env:
            - name: "PASSWORD"
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: PASSWORD
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/usr/share/nginx/html/index.html"
              subPath: index.html

