apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
   app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      name: http